### ISSUE TITLE
Virus total showing hits as infected?

### ISSUE THREAD

**Issue by quarinteen** [stefan-wr/keplers-updater-for-wxtoimg#1]
I just ran this updater through virus total and it marked it as hot. Any explanation as to why?

https://www.virustotal.com/gui/file/c1989ac3febd8d1763be9d1dd19f3d01a4c7294b3789252014d5485c08a12372

**Comment by stefan-wr** [comment]
I wrote this updater in Python. To make it easier to distribute I used [PyInstaller](https://github.com/pyinstaller/pyinstaller) to bundle the script into a single-file-executable.

Such executables created by pyinstaller can cause false positives with anti-virus software due to their common bootloader:
https://github.com/pyinstaller/pyinstaller/issues/6754#issuecomment-1100821249

The only way to avoid false positives would be to sign the executable, which requires a paid certificate.
